# Generated by Django 5.2.4 on 2025-07-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yougile', '0002_project_company_project_trackable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='api_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='api_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='api_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ycolumn',
            name='api_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
