# Generated by Django 5.2.4 on 2025-07-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yougile', '0003_alter_board_api_id_alter_project_api_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ycolumn',
            name='color',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
