# Generated by Django 5.2.4 on 2025-08-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yougile', '0004_alter_ycolumn_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
