# Generated by Django 5.2.4 on 2025-08-06 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yougile', '0005_task_description_alter_task_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='arhived',
            new_name='archived',
        ),
    ]
