# Generated by Django 5.2.4 on 2025-08-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yougile', '0006_rename_arhived_task_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
